### ISSUE TITLE
MENU/BACK button tip

### ISSUE THREAD

**Issue by NuClear235** [TomDDG/ZXPicoMD#10]
Hello,
I feel user interface unfriendly because of Display on by press ENTER button.

Could You reprogram it for using button BACK to Display ON, please? 
It makes BACK button as “MENU/BACK” button. 

On some devices is it so and is it fine…

**Comment by TomDDG** [comment]
I can easily add an option in the next update so users can choose whether they want ENTER or BACK to be the menu button.

**Comment by NuClear235** [comment]
Perfect solution

**Comment by TomDDG** [comment]
I might also just make it so back or enter go into the menu

**Comment by NuClear235** [comment]
Need to try.

**Comment by TomDDG** [comment]
As of v1.7 Back button now works to enter the menu
