### ISSUE TITLE
MD number as submenu

### ISSUE THREAD

**Issue by NuClear235** [TomDDG/ZXPicoMD#11]
Would not be good add one icon “MD X”?
When enter to it, so THEN will be possible to select MD1 - MD8…
<img width="829" alt="MD2 0" src="https://github.com/TomDDG/ZXPicoMD/assets/19590199/2b40adbe-771a-44b9-82e3-0053d79abb43">

**Comment by NuClear235** [comment]
Prev/Next is rotating in menu and now is entering to MD numbers. Non standard behaviour? 
I am ussually using Next to display menu items and It does not work so :-)

**Comment by TomDDG** [comment]
Thanks for the suggestion. I'm not planning on putting the cartridges in a new sub-menu. There isn't any options to the right of the cartridge selection icons so they are already in their own section, all other menu items will the in the left hand section. 

Will mark this as closed but please do make other suggestions as I will definitely consider them.
