### ISSUE TITLE
Fantastic project

### ISSUE THREAD

**Issue by marvbloke** [TomDDG/ZXPicoMD#3]
Hi Tom,

This is a great use of the Pico to replace aging hardware that can go wrong. The next logical step would be to create a Pico drop-in replacement for the Interface 1 itself, given how expensive, rare and prone to failure the originals are. My own hardware/software skills are not up to the task, but given your work on the ZXPicoMD, I wouldn't be surprised if you were already working on it! Would love it to retain all the functionality including the network interface and RS232 etc.

Regards,
Matthew Begg

**Comment by TomDDG** [comment]
Thanks. IF1 is definitely on my list and in fact I've already started this journey by looking at the IF2 and switching ROMs. You can check this out here https://github.com/TomDDG/ZXPicoIF2ROM
