### ISSUE TITLE
Excellent work, some help needed

### ISSUE THREAD

**Issue by kladogen** [TomDDG/ZXPicoMD#4]
Hi TomDDG,

I'm working on a project for about a year now trying to make something similar for the QL. Initially I started with an ESP32 and now I'm using al Rasperry Pico because it can load in memory the whole MDV image. I have made a board similar to yours, although I have added a 74LS125 quad buffer to have better driving & control of the QL mdv lines.   Although I have made some progress, ie I can the detect the drive requested from the QL, when I start sending data the QL just waits for ever. I have checked exhaustively with an oscilloscope the data format on TRACK1, TRACk2 and the timings and they all seem correct. I know you are not interested in developing something for the QL but any help would be welcome since I have run out of ideas. Have you seen anything similar on the spectrum I/F? What is the correct order to send the sectors? Although I have tried both directions (i.e. MDV sector number # increasing and decreasing) the result is the same.

Regards

Antonis
kladogen@gmail.com

**Comment by TomDDG** [comment]
Sectors need to be sent high to low and then loop. You also need a pause before starting the data tracks and between sectors. Unfortunately I'm not too familiar with the way the QL does this but I do know it uses different (faster) timing to the Spectrum, switches the tracks and has different sector gaps. I'd highly recommend having a look at the Oqtadrive code, which is opensource, and website as Alex has spent a lot of time getting the QL working https://oqtadrive.org/09.background/development/

**Comment by TomDDG** [comment]
I can also put you in touch with Alex if you would like as he is very helpful and my project wouldn't be here without his support.

**Comment by kladogen** [comment]
Thanks allot TomDDG. I have already looked into oqtadrive and I have built one that's working correctly, however its not what I want, I prefer something like your device for the spectrum. I have looked in depth to the oqtqdrive code and also on  the I/F with an oscilloscope trying to find the difference between my signals and theirs - I did not manage to find it. The only difference I found was the gap between sectors that according to the QL manual should be 5.5ms but the oqtadrive is 7.2ms. Also I have looked to the code given by gertk on https://qlforum.co.uk/viewtopic.php?t=584 - no luck either. I will try to contact them, maybe they have some tips.

Thanks again, 
Antonis

**Comment by kladogen** [comment]
If you could get me in touch with Alex it would be great. My email is kladogen@gmail.com.

**Comment by TomDDG** [comment]
Do you have a GutHub or webpage I can point Alex to?

**Comment by kladogen** [comment]
Hi I have just created an organization on github https://github.com/kladogenA and a project mdrive. I would be gratefull if he can contact me there.

**Comment by kladogen** [comment]
Hi again, any news from Alex?

**Comment by TomDDG** [comment]
I've passed all the info to him, guess he's just not had time yet. Recommend you ping him on the Oqtadrive thread on the QL forum https://www.qlforum.co.uk/viewtopic.php?t=4056&start=110 as he usually responds to those.
