### ISSUE TITLE
Source code for Pico missing

### ISSUE THREAD

**Issue by thiseldo** [TomDDG/ZXPicoMD#5]
The fully buildable source code for the Pico is not present, only a few snippets.
I'm trying to determine the reason for an OLED display is not operating correctly when the display works ok on another Pico using different software.

**Comment by thiseldo** [comment]
I bought PCBs via PCBway and have OLED with GND, Vcc, SCL and SDA as you have them.  Display responds to address 0x3C when using I2C scanner.

**Comment by TomDDG** [comment]
Can you put a multimeter on the 4pin header and make sure 3v3 is supplied and continuity on the other pins with the Pico? The circuit is extremely simple for the OLED and the software to drive also, so difficult to know what could be wrong other than hardware. Do you get anything on the screen at all? Does the rest of the device work, LEDs come on etc...? How do you know the Pico flashed ok?

Can you check the settings used for the other software that works, wondering if it is the frequency. PicoMD uses 400KHz but that might not be compatible with your OLED model?

**Comment by thiseldo** [comment]
Looks like a dodgy soldering joint on the SDA pin at the Pico end.
I had identified the pico working because it was accessing the uSD card, set up the 8 carts and was flashing the LED when no card was inserted.

It would still be good to have the full code.

**Comment by TomDDG** [comment]
Glad you got it working, closing issue as resolved.
