### ISSUE TITLE
Optional bigger OLED 1309

### ISSUE THREAD

**Issue by NuClear235** [TomDDG/ZXPicoMD#8]
Please add support for bigger OLED display 1309.
https://www.banggood.com/cs/1_54-inch-OLED-Display-LCD-Screen-Module-Resolution-128+64-SPI-or-IIC-Interface-SSD1309-Driver-p-1963995.html?channel=googleshopping&utm_source=googleshopping&utm_medium=cpc_eu&utm_campaign=aceng-pmax-pl-cz-level-1-cae-240221&utm_content=dcr&af_force_deeplink=true&fbclid=IwAR2zLoOQjq8DBjB_jMNvhQj7GXFG5V2x3BMnPFlpyehrjrUPRDijfKIoHNI&tags=direct&source_caller=api&pid=googleshopping&is_retargeting=true&shortlink=9bjl9m5b&af_ad=dcr&deep_link_value=banggood%3A%2F%2Fprod-1963995%3Fchannel%3Dgoogleshopping%26utm_source%3Dgoogleshopping%26utm_medium%3Dcpc_eu%26utm_campaign%3Daceng-pmax-pl-cz-level-1-cae-240221%26utm_content%3Ddcr&af_channel=cpc_eu&c=aceng-pmax-pl-cz-level-1-cae-240221

**Comment by TomDDG** [comment]
OLEDs ordered to test. Quick look at the data instructions and it seems to be the same as the current SSD1306 so fingers crossed it is a straight drop in replacement. 

I have read that the screen may need some modifications but that may be for the SPI version so again will check once they arrive.

**Comment by TomDDG** [comment]
Tested working fine with a 4 pin I2C 1.54" SSD1309, no changes to the code required.
